language: node_js
addons:
  chrome: stable
before_install:
  - npm install -g express
  - npm install
script:
  #- npm start # build your site
  - echo "$DOCKER_PASSWORD" | docker login -u "$DOCKER_USERNAME" --password-stdin
  - docker build -t qiongyuxiliang/docker-test:latest
  - docker push qiongyuxiliang/docker-test:latest

