version: "2" 
services:
    infos:
        container_name: docker-test 
        image: docker-test:latest
        volumes:
        - ./:/usr/local/app
        restart: on-failure
        working_dir: /usr/local/app
        ports:
        - 8090:8090
        command: npm start
